controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gantry_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


gantry_controller:
  ros__parameters:
    joints:
      - y_joint
      - x_joint
      - z_joint
      - wrist_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false


gripper_controller:
  ros__parameters:
    joints:
      - left_finger_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
